seed : 42
batch_size : 4
epochs : 100
lr : 0.001
weight_decay : 0.1
early_stopping_patience : 8

model : {
  type : temporal,
  name : sew_resnet18_spiking,
  spiking_params : {
    neuron_model : plif,
    surrogate_function : sigmoid,
    n_samples : 30,
    step_mode : multi_step,
    backend : torch,
    
  }
}

dataset : {
  root_path : ./datasets/jaad2/dvs_decay/good_weather/,
  dvs_mode : True,
  type : temporal,
  img_width : 256,
  img_height : 450,
  evaluation_mode : standard, # or kfold
  n_folds : 5, # only used if evaluation_mode is kfold
  val_size : 0.15, # always used
  test_size : 0.15, # only used if evaluation_mode is standard
  timestep : 30,
  overlap : 29,
  repeats : 10,
  n_frames_predictive_horizon : 150 # only used if type is prediction
}

wandb : {
  entity : ml_agh,
  project : jaad_experiments,
  group : 2nd_paper_experiments,
}

checkpoint_path : checkpoints_lightning
dataset_save_dir : results_new_runs/datasets # save the test data for every fold (or entire run)
#checkpoint_dir_to_restore : checkpoints_lightning/c3db4633-b900-42be-9dfe-c0916f06018a















