seed : 42
batch_size : 16
epochs : 100
lr : 0.001
weight_decay : 0.1
early_stopping_patience : 8

model : {
  type : temporal,
  name : sew_resnet18_spiking,
  spiking_params : {
    neuron_model : plif,
    surrogate_function : sigmoid,
    n_samples : 9,
    step_mode : multi_step,
    backend : torch,
    
  }
}

dataset : {
  root_path : ./datasets/dataset_jaad/silver_dvs_bad_weather/, 
  dvs_mode : True,
  type : temporal,
  img_width : 256,
  img_height : 450,
  evaluation_mode : standard, # or kfold
  n_folds : 5, # only used if evaluation_mode is kfold
  val_size : 0.15, # always used
  test_size : 0.15, # only used if evaluation_mode is standard
  timestep : 9, # only used if type is temporal  #30
  overlap : 8, # only used if type is temporal  #29
  repeats : 10,
  n_frames_predictive_horizon : 150 # only used if type is prediction
}

wandb : {
  entity : ml_agh,
  project : jaad_experiments,
  group : 2nd_paper_experiments,
}

checkpoint_path : checkpoints_lightning
dataset_save_dir : results_new_runs/datasets # save the test data for every fold (or entire run)
#checkpoint_dir_to_restore : checkpoints_lightning/8e7a9d93-7575-4272-82f2-3bbb9dd35e75















